### ISSUE TITLE
Vulnerability due to implicit prismjs dependency

### ISSUE THREAD

**Issue by henningko** [ymmooot/markduck#12]
Due to the dependency on an old version of @mapbox/rehype-prism (and implicitly, prismjs), this package has a 'moderate' vulnerability:
https://www.npmjs.com/advisories/1638

There's an updated rehype-prism available (≥ 0.5.0 should fix it).

(Thanks for a really helpful tool 👍 )

**Comment by ymmooot** [comment]
@henningko Thank you!
I will update package dependencies.
